In [4]:
import numpy as np

In [4]:
np.logspace(-5,0,6)

[1e-05, 0.0001, 0.001, 0.01, 0.1, 1.0]

In [8]:
np.array([1,2,3])[np.array([True,False,True])]

array([1, 3])

In [11]:
np.log2([12,24])

array([3.5849625, 4.5849625])

In [1]:
import seaborn as sns

In [2]:
sns.color_palette()

[(0.12156862745098039, 0.4666666666666667, 0.7058823529411765),
 (1.0, 0.4980392156862745, 0.054901960784313725),
 (0.17254901960784313, 0.6274509803921569, 0.17254901960784313),
 (0.8392156862745098, 0.15294117647058825, 0.1568627450980392),
 (0.5803921568627451, 0.403921568627451, 0.7411764705882353),
 (0.5490196078431373, 0.33725490196078434, 0.29411764705882354),
 (0.8901960784313725, 0.4666666666666667, 0.7607843137254902),
 (0.4980392156862745, 0.4980392156862745, 0.4980392156862745),
 (0.7372549019607844, 0.7411764705882353, 0.13333333333333333),
 (0.09019607843137255, 0.7450980392156863, 0.8117647058823529)]

In [6]:
np.ceil(np.linspace(0,10,77))

array([ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.,  7.,  7.,
        7.,  7.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  9.,  9.,  9.,  9.,
        9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.])

In [7]:
import pandas as pd

In [33]:
x = np.random.random(50)

In [34]:
s = pd.Series(x).rank(pct=True)

In [36]:
print s.head()
print (np.ceil(10*s).astype(int)).head()

0    0.04
1    0.46
2    0.88
3    0.68
4    0.78
dtype: float64
0    1
1    5
2    9
3    7
4    8
dtype: int64


In [31]:
help(s.rank)

Help on method rank in module pandas.core.generic:

rank(self, axis=0, method='average', numeric_only=None, na_option='keep', ascending=True, pct=False) method of pandas.core.series.Series instance
    Compute numerical data ranks (1 through n) along axis. Equal values are
    assigned a rank that is the average of the ranks of those values
    
    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        index to direct ranking
    method : {'average', 'min', 'max', 'first', 'dense'}
        * average: average rank of group
        * min: lowest rank in group
        * max: highest rank in group
        * first: ranks assigned in order they appear in the array
        * dense: like 'min', but rank always increases by 1 between groups
    numeric_only : boolean, default None
        Include only float, int, boolean data. Valid only for DataFrame or
        Panel objects
    na_option : {'keep', 'top', 'bottom'}
        * keep: leave NA values where they ar

In [1]:
d = {'a': 1, 'b': 2}

In [5]:
import json

In [6]:
with open('../json_and_txt/mktg_events.json', 'r') as f:
    events = json.load(f)

In [8]:
e = 'anniversary_public_event'
filter(lambda d: d['event']==e, events)

[{u'event': u'anniversary_public_event',
  u'event_slug': u'annpub',
  u'short_event': u'anniversary_public'}]

In [9]:
2017%1000

17

In [1]:
import pandas as pd
import numpy as np

In [16]:
gp = ['5','4','3','2','1']

In [23]:
x = pd.DataFrame(np.random.rand(5,2), index=pd.Index(gp, name='persona'))
x

0         1
persona                    
5        0.373053  0.418269
4        0.480451  0.234924
3        0.817707  0.221697
2        0.796248  0.168060
1        0.525676  0.760720

In [24]:
x.sort_index()

0         1
persona                    
1        0.525676  0.760720
2        0.796248  0.168060
3        0.817707  0.221697
4        0.480451  0.234924
5        0.373053  0.418269

In [27]:
def tests(slug = 2, **kwargs):
    print slug
    print kwargs

In [28]:
d = {'a': 1, 'b': 'dennis', 'slug': 0.8}
tests(**d)

0.8
{'a': 1, 'b': 'dennis'}


In [103]:
y = np.random.rand(10)*120

In [94]:
z = np.floor(y) # - y.min())

In [95]:
q = np.log1p(z)
(q-q.min())/(q.max()-q.min())

array([0.36907025, 0.83404377, 0.83404377, 0.63092975, 0.36907025,
       0.        , 1.        , 0.36907025, 1.        , 0.36907025])

In [98]:
q = np.log(z)
(q-q.min())/(q.max()-q.min())

array([0.43067656, 0.86135312, 0.86135312, 0.68260619, 0.43067656,
       0.        , 1.        , 0.43067656, 1.        , 0.43067656])

In [96]:
q = z.copy()
q[q <= 0] = -1
q[q > 0] = np.log(q[q > 0])
(q-q.min())/(q.max()-q.min())

array([0.43067656, 0.86135312, 0.86135312, 0.68260619, 0.43067656,
       0.        , 1.        , 0.43067656, 1.        , 0.43067656])

In [97]:
z

array([2., 4., 4., 3., 2., 1., 5., 2., 5., 2.])

In [99]:
def logm1(x):
    y = x.copy()
    x[x <= 0] = -1
    x[x > 0] = np.log(x[x > 0])
    return x

In [100]:
logm1(z)

array([0.69314718, 1.38629436, 1.38629436, 1.09861229, 0.69314718,
       0.        , 1.60943791, 0.69314718, 1.60943791, 0.69314718])

In [102]:
(z <= 0).any()

True

In [107]:
w = pd.Series(y)

In [108]:
np.where(w > 96, 1, w/96)

array([1.        , 1.        , 0.81619403, 0.3496892 , 0.08873599,
       1.        , 1.        , 1.        , 0.69243683, 0.4249961 ])

In [111]:
np.fmin(w/96, 1)

0    1.000000
1    1.000000
2    0.816194
3    0.349689
4    0.088736
5    1.000000
6    1.000000
7    1.000000
8    0.692437
9    0.424996
dtype: float64

In [113]:
d = {'a': 1, 'b': 2}
l = list('cdef')
n = 3
d.update([(m,n) for m in l])
d

{'a': 1, 'b': 2, 'c': 3, 'd': 3, 'e': 3, 'f': 3}

In [2]:
xx = np.random.rand(8,5)*10
yy = np.where(xx < 1, np.nan, np.floor(xx))
zz = pd.DataFrame(yy).to_csv(None, header=False, index=False, float_format='%.0f')

In [12]:
import StringIO

In [15]:
ww = pd.read_csv(StringIO.StringIO(zz), header=None, dtype='O')

In [16]:
print ww.to_csv(None, header=False, index=False)

1,7,1,,5
7,6,,,
2,,2,3,8
1,4,6,,7
2,6,7,4,7
2,9,5,9,6
,8,7,5,4
5,,5,7,5



In [23]:
zz = pd.DataFrame(yy)

In [27]:
zz[zz.notnull()] = zz.applymap('{:.0f}'.format)

In [28]:
zz.to_csv(None, header=False, index=False)

'8,8,9,2,7\n1,2,,6,1\n9,6,,,7\n,1,9,,4\n4,8,7,3,3\n2,,8,,8\n5,7,7,8,\n,3,6,5,6\n'